<?php 
class pending_ledgers_default_schema {
    public $fields = array(
        'id',
        'reseller_id',
        'account_id',
        'src_bank_id',
        'dst_bank_id',
        'amount',
        'balance_after',
        'cur_id',
        'rate',
        'product_id',
        'category_id',
        'tr_date',
        'description',
        'type',
        'created_by',
        'product_rate',
        'reseller_rate',
        'deposit',
        'deposit_cur_id',
        'is_posted',
        'bank_balance_after',
        'update_info',
        'invoice_id',
        'res_payment_id',
        'res_old_amount',
        'sync_flag',
        'keep',
    );
    
    public $validate = array(
        'id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'reseller_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'account_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'src_bank_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'dst_bank_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'amount' => array('double'=>array("precision"=>array("M"=>20, "D"=>4)),),
        'balance_after' => array('double'=>array("precision"=>array("M"=>20, "D"=>4)),),
        'cur_id' => array('length'=>array('max'=>5),),
        'rate' => array('double'=>array("precision"=>array("M"=>10, "D"=>4)),),
        'product_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'category_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'tr_date' => array('datetime'=>array(),),
        'description' => array('length'=>array('max'=>500),),
        'type' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'created_by' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'product_rate' => array('double'=>array("precision"=>array("M"=>10, "D"=>4)),),
        'reseller_rate' => array('double'=>array("precision"=>array("M"=>10, "D"=>4)),),
        'deposit' => array('double'=>array("precision"=>array("M"=>20, "D"=>4)),),
        'deposit_cur_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'is_posted' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'bank_balance_after' => array('double'=>array("M"=>11, "D"=>4),),
        'update_info' => array(),
        'invoice_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'res_payment_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'res_old_amount' => array('double'=>array("precision"=>array("M"=>20, "D"=>4)),),
        'sync_flag' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'keep' => array('int'=>array(),'range'=>array('min'=>-128, 'max'=>127),),
    );

    public $field_type = array(
        'id' => 'INT',
        'reseller_id' => 'INT',
        'account_id' => 'INT',
        'src_bank_id' => 'INT',
        'dst_bank_id' => 'INT',
        'amount' => 'DOUBLE',
        'balance_after' => 'DOUBLE',
        'cur_id' => 'VARCHAR',
        'rate' => 'DOUBLE',
        'product_id' => 'INT',
        'category_id' => 'INT',
        'tr_date' => 'TIMESTAMP',
        'description' => 'VARCHAR',
        'type' => 'INT',
        'created_by' => 'INT',
        'product_rate' => 'DOUBLE',
        'reseller_rate' => 'DOUBLE',
        'deposit' => 'DOUBLE',
        'deposit_cur_id' => 'INT',
        'is_posted' => 'INT',
        'bank_balance_after' => 'DECIMAL',
        'update_info' => 'TEXT',
        'invoice_id' => 'INT',
        'res_payment_id' => 'INT',
        'res_old_amount' => 'DOUBLE',
        'sync_flag' => 'INT',
        'keep' => 'TINYINT',
    );

    public $php_type = array(
        'id' => 'int',
        'reseller_id' => 'int',
        'account_id' => 'int',
        'src_bank_id' => 'int',
        'dst_bank_id' => 'int',
        'amount' => 'double',
        'balance_after' => 'double',
        'cur_id' => 'string',
        'rate' => 'double',
        'product_id' => 'int',
        'category_id' => 'int',
        'tr_date' => 'string',
        'description' => 'string',
        'type' => 'int',
        'created_by' => 'int',
        'product_rate' => 'double',
        'reseller_rate' => 'double',
        'deposit' => 'double',
        'deposit_cur_id' => 'int',
        'is_posted' => 'int',
        'bank_balance_after' => 'double',
        'update_info' => 'string',
        'invoice_id' => 'int',
        'res_payment_id' => 'int',
        'res_old_amount' => 'double',
        'sync_flag' => 'int',
        'keep' => 'int',
    );
}

