<?php 
class resellers_default_schema {
    public $fields = array(
        'id',
        'old_id',
        'server_id',
        'idReseller',
        'login',
        'password',
        'level',
        'client_type',
        'type',
        'callsLimit',
        'fullname',
        'address',
        'city',
        'zipcode',
        'country',
        'phone',
        'email',
        'table_type',
        'account_state',
        'customer_id',
        'rate',
        'status',
    );
    
    public $validate = array(
        'id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'old_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'server_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'idReseller' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'login' => array('length'=>array('max'=>20),),
        'password' => array('length'=>array('max'=>20),),
        'level' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'client_type' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'type' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'callsLimit' => array('double'=>array("M"=>12, "D"=>4),),
        'fullname' => array('length'=>array('max'=>200),),
        'address' => array('length'=>array('max'=>200),),
        'city' => array('length'=>array('max'=>50),),
        'zipcode' => array('length'=>array('max'=>20),),
        'country' => array('length'=>array('max'=>5),),
        'phone' => array('length'=>array('max'=>50),),
        'email' => array('length'=>array('max'=>200),),
        'table_type' => array('in(\'1\',\'2\')',),
        'account_state' => array('double'=>array("M"=>12, "D"=>4),),
        'customer_id' => array('int'=>array(),'range'=>array('min'=>-2147483648, 'max'=>2147483647),),
        'rate' => array('double',),
        'status' => array('int'=>array(),'range'=>array('min'=>-128, 'max'=>127),),
    );

    public $field_type = array(
        'id' => 'INT',
        'old_id' => 'INT',
        'server_id' => 'INT',
        'idReseller' => 'INT',
        'login' => 'CHAR',
        'password' => 'CHAR',
        'level' => 'INT',
        'client_type' => 'INT',
        'type' => 'INT',
        'callsLimit' => 'DECIMAL',
        'fullname' => 'CHAR',
        'address' => 'CHAR',
        'city' => 'CHAR',
        'zipcode' => 'CHAR',
        'country' => 'VARCHAR',
        'phone' => 'CHAR',
        'email' => 'CHAR',
        'table_type' => 'ENUM',
        'account_state' => 'DECIMAL',
        'customer_id' => 'INT',
        'rate' => 'DOUBLE',
        'status' => 'TINYINT',
    );

    public $php_type = array(
        'id' => 'int',
        'old_id' => 'int',
        'server_id' => 'int',
        'idReseller' => 'int',
        'login' => 'string',
        'password' => 'string',
        'level' => 'int',
        'client_type' => 'int',
        'type' => 'int',
        'callsLimit' => 'double',
        'fullname' => 'string',
        'address' => 'string',
        'city' => 'string',
        'zipcode' => 'string',
        'country' => 'string',
        'phone' => 'string',
        'email' => 'string',
        'table_type' => 'string',
        'account_state' => 'double',
        'customer_id' => 'int',
        'rate' => 'double',
        'status' => 'int',
    );
}

